networks:
  pr:
    driver: bridge
    name: pr

services:
  pr_mania-ui:
    networks:
      - pr
    build: ./fe
    ports:
      - '3000:3001'
    container_name: pr_mania-ui
    restart: always
    volumes:
      - ./fe:/app
      - /app/node_modules

  pr_mania-api:
    networks:
      - pr
    build: ./api
    ports:
      - '8000:8000'
    container_name: pr_mania-api
    restart: always
