networks:
  pr:
    driver: bridge
    name: pr

services:
  pr_data-store:
    networks:
      - pr
    container_name: pr_data-store
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27012:27017'

  pr_mania-ui:
    networks:
      - pr
    build: ./fe
    ports:
      - '3000:3000'
    image: pr_mania-ui
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_WS_URL: ws://localhost:8000
    # volumes:
    # - .node_modules:/app/node_modules
    # - .:/app
    container_name: pr_mania-ui
    restart: always

  pr_mania-api:
    networks:
      - pr
    build: ./api
    image: pr_mania-api
    ports:
      - '8000:8000'
    container_name: pr_mania-api
    restart: always
